name: Publish Dashboard

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "update/**"

jobs:
  publish_pages:
    name: Publish to git-pages
    runs-on: ubuntu-node
    steps:
      - name: Clone repo
        run: |
          git clone --depth 1 -b main http://oauth2:${{ secrets.FORGE_TOKEN }}@git.repodata.economiayfinanzas.gob.bo/mefp-uie/vuelos.git .

      - name: Build Dashboard Dataset
        run: |
          python -m pip install -r update/requirements.txt
          python update/build_dashboard_dataset.py

      - name: Temporary hosts entry for git-pages
        run: |
          echo "172.20.249.55 pages.repodata.economiayfinanzas.gob.bo" >> /etc/hosts

      - name: Publish to git-pages
        uses: http://git.repodata.economiayfinanzas.gob.bo/mefp-uie/git-pages-action@v2
        with:
          site: "http://pages.repodata.economiayfinanzas.gob.bo/mefp-uie/vuelos/"
          token: ${{ forge.token }}
          source: docs
