name: Update pasajes data

on:
  schedule:
    - cron: "9 8,12 * * *"
  workflow_dispatch:

jobs:
  update:
    name: update pasajes data
    runs-on: ubuntu-node
    steps:
      - name: Clone repo
        run: |
          git clone --depth 1 -b main http://oauth2:${{ secrets.FORGE_TOKEN }}@git.repodata.economiayfinanzas.gob.bo/mefp-uie/vuelos.git .

      - name: install python and dependencies
        run: |
          apt-get update && apt-get install -y python3-pip
          python3 -m pip install --break-system-packages -r update/requirements.txt

      - name: run update script
        env:
          CKAN_URL: http://ckan:5000
          CKAN_ACCESS_KEY: ${{ secrets.CKAN_ACCESS_KEY }}
          S3_ENDPOINT: http://aistor:9000
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: |
          python3 update/fetch_pasajes.py

  publish_pages:
    name: Publish Dashboard
    needs: update
    runs-on: ubuntu-node
    steps:
      - name: Clone repo
        run: |
          git clone --depth 1 -b main http://oauth2:${{ secrets.FORGE_TOKEN }}@git.repodata.economiayfinanzas.gob.bo/mefp-uie/vuelos.git .

      - name: Build Dashboard Dataset
        run: |
          apt-get update && apt-get install -y python3-pip
          python3 -m pip install --break-system-packages -r update/requirements.txt
          python3 update/build_dashboard_dataset.py

      - name: Temporary hosts entry for git-pages
        run: |
          echo "172.20.249.55 pages.repodata.economiayfinanzas.gob.bo" >> /etc/hosts

      - name: Publish to git-pages
        uses: http://git.repodata.economiayfinanzas.gob.bo/mefp-uie/git-pages-action@v2
        with:
          site: "http://pages.repodata.economiayfinanzas.gob.bo/mefp-uie/vuelos/"
          token: ${{ forge.token }}
          source: docs
